import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ExportOptions {
  title: string;
  subtitle?: string;
  data: any;
  type: 'ai-detection' | 'grammar' | 'plagiarism' | 'batch' | 'general';
}

export function exportToPDF(options: ExportOptions) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235); // Blue
  doc.text(options.title, pageWidth / 2, 20, { align: 'center' });

  if (options.subtitle) {
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(options.subtitle, pageWidth / 2, 28, { align: 'center' });
  }

  let yPos = 40;

  // Content based on type
  switch (options.type) {
    case 'ai-detection':
      yPos = addAIDetectionContent(doc, options.data, yPos);
      break;
    case 'grammar':
      yPos = addGrammarContent(doc, options.data, yPos);
      break;
    case 'plagiarism':
      yPos = addPlagiarismContent(doc, options.data, yPos);
      break;
    case 'batch':
      yPos = addBatchContent(doc, options.data, yPos);
      break;
    default:
      yPos = addGeneralContent(doc, options.data, yPos);
  }

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      `Generated by OriginLytics - Page ${i} of ${pageCount} - ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Download
  const filename = `${options.title.replace(/\s+/g, '-')}-${Date.now()}.pdf`;
  doc.save(filename);
}

function addAIDetectionContent(doc: jsPDF, data: any, yPos: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  // AI Score
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text('AI Detection Score', 15, yPos);
  yPos += 10;

  doc.setFontSize(48);
  const scoreColor = data.score < 30 ? [34, 197, 94] : data.score < 70 ? [234, 179, 8] : [239, 68, 68];
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(`${data.score}%`, 15, yPos);
  yPos += 15;

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(data.verdict || 'Analysis Complete', 15, yPos);
  yPos += 15;

  // Summary
  if (data.summary) {
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.text('Summary:', 15, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.setTextColor(60);
    const summaryLines = doc.splitTextToSize(data.summary, pageWidth - 30);
    doc.text(summaryLines, 15, yPos);
    yPos += summaryLines.length * 5 + 10;
  }

  return yPos;
}

function addGrammarContent(doc: jsPDF, data: any, yPos: number): number {
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`Found ${data.errors?.length || 0} issues`, 15, yPos);
  yPos += 10;

  if (data.errors && data.errors.length > 0) {
    autoTable(doc, {
      startY: yPos,
      head: [['Type', 'Issue', 'Suggestion']],
      body: data.errors.slice(0, 50).map((e: any) => [
        e.type || 'N/A',
        e.message?.substring(0, 60) || 'N/A',
        e.replacements?.[0]?.substring(0, 40) || 'N/A'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 9 }
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  return yPos;
}

function addPlagiarismContent(doc: jsPDF, data: any, yPos: number): number {
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text(`Uniqueness Score: ${data.uniqueScore || 0}%`, 15, yPos);
  yPos += 15;

  if (data.matches && data.matches.length > 0) {
    doc.setFontSize(14);
    doc.text('Potential Matches:', 15, yPos);
    yPos += 10;

    autoTable(doc, {
      startY: yPos,
      head: [['Source', 'Similarity', 'URL']],
      body: data.matches.slice(0, 20).map((m: any) => [
        m.title?.substring(0, 40) || 'N/A',
        `${m.similarity || 0}%`,
        m.url?.substring(0, 50) || 'N/A'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 9 }
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(12);
    doc.setTextColor(34, 197, 94);
    doc.text('✓ No plagiarism detected', 15, yPos);
    yPos += 10;
  }

  return yPos;
}

function addBatchContent(doc: jsPDF, data: any[], yPos: number): number {
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`Batch Results (${data.length} files)`, 15, yPos);
  yPos += 10;

  if (data && data.length > 0) {
    autoTable(doc, {
      startY: yPos,
      head: [['Filename', 'Status', 'Words', 'Result']],
      body: data.map((item: any) => [
        item.filename?.substring(0, 30) || 'N/A',
        item.status || 'N/A',
        item.wordCount?.toLocaleString() || 'N/A',
        item.score !== undefined ? `${item.score}%` : item.error || 'Processed'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 9 }
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  return yPos;
}

function addGeneralContent(doc: jsPDF, data: any, yPos: number): number {
  doc.setFontSize(12);
  doc.setTextColor(0);

  // Convert data object to key-value pairs
  const entries = Object.entries(data);

  for (const [key, value] of entries) {
    doc.text(`${key}: ${String(value)}`, 15, yPos);
    yPos += 7;

    // New page if needed
    if (yPos > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      yPos = 20;
    }
  }

  return yPos;
}
