import { useEffect } from 'react';
import { AIDetector } from './AIDetector';

// ChatGPTDetector is an alias for AIDetector with ChatGPT-focused SEO metadata
export function ChatGPTDetector() {
  useEffect(() => {
    // Override SEO meta tags for this page
    document.title = 'ChatGPT Detector - Detect ChatGPT Text | OriginLytics';

    const setMetaTag = (name: string, content: string) => {
      let tag = document.querySelector(`meta[name="${name}"]`);
      if (!tag) {
        tag = document.createElement('meta');
        tag.setAttribute('name', name);
        document.head.appendChild(tag);
      }
      tag.setAttribute('content', content);
    };

    const setPropertyTag = (property: string, content: string) => {
      let tag = document.querySelector(`meta[property="${property}"]`);
      if (!tag) {
        tag = document.createElement('meta');
        tag.setAttribute('property', property);
        document.head.appendChild(tag);
      }
      tag.setAttribute('content', content);
    };

    setMetaTag('description', 'Free ChatGPT detector. Check if text was written by ChatGPT, GPT-4, or GPT-3.5. Instant AI detection with no signup required.');
    setMetaTag('keywords', 'chatgpt detector, detect chatgpt, gpt detector, chatgpt checker, gpt-4 detector, detect gpt text');
    setPropertyTag('og:title', 'ChatGPT Detector - Detect ChatGPT Generated Text');
    setPropertyTag('og:description', 'Free ChatGPT detector. Instantly check if content was generated by ChatGPT or written by a human.');
  }, []);

  return <AIDetector />;
}
