// Footer Tools Data
// Comprehensive tool catalog for interactive footer navigation

import type { Tool, ToolCategoryGroup } from '../types/footer';
import { ToolCategory } from '../types/footer';

/**
 * Complete tool catalog
 */
export const FOOTER_TOOLS: Tool[] = [
  {
    id: 'ai-detector',
    name: 'AI Detector',
    icon: '🤖',
    path: '/ai-detector',
    category: ToolCategory.AI_DETECTION,
    description: 'Detect AI-generated content with industry-leading accuracy using advanced machine learning algorithms.',
    features: [
      '95%+ accuracy rate',
      'Multi-model detection (GPT, Claude, Gemini)',
      'Detailed confidence scoring',
      'Sentence-by-sentence analysis'
    ],
    longDescription: 'Our flagship AI detection tool uses state-of-the-art machine learning to identify content generated by ChatGPT, Claude, Gemini, and other AI models.',
    isPopular: true
  },
  {
    id: 'paraphraser',
    name: 'Paraphraser',
    icon: '✍️',
    path: '/paraphraser',
    category: ToolCategory.WRITING_TOOLS,
    description: 'Rewrite text while preserving meaning with multiple tone options and style variations.',
    features: [
      'Multiple rewriting modes',
      'Tone adjustment (formal, casual, creative)',
      'Plagiarism-free output',
      'Instant results'
    ],
    longDescription: 'Transform your writing with intelligent paraphrasing that maintains your original meaning while improving clarity and style.'
  },
  {
    id: 'summarizer',
    name: 'Summarizer',
    icon: '📚',
    path: '/summarizer',
    category: ToolCategory.WRITING_TOOLS,
    description: 'Generate concise summaries from long texts with adjustable length and key point extraction.',
    features: [
      'Adjustable summary length',
      'Key point extraction',
      'Bullet point format option',
      'Preserves critical information'
    ],
    longDescription: 'Quickly distill lengthy documents into concise, readable summaries.'
  },
  {
    id: 'grammar-checker',
    name: 'Grammar Checker',
    icon: '📝',
    path: '/grammar-checker',
    category: ToolCategory.WRITING_TOOLS,
    description: 'Identify and fix grammar, spelling, and punctuation errors with intelligent suggestions.',
    features: [
      'Real-time error detection',
      'Contextual suggestions',
      'Style improvement tips',
      'Advanced punctuation checking'
    ],
    longDescription: 'Eliminate grammar mistakes and improve your writing quality.'
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    icon: '🔢',
    path: '/word-counter',
    category: ToolCategory.ANALYSIS_TOOLS,
    description: 'Comprehensive text analysis with word count, character count, and readability metrics.',
    features: [
      'Real-time word/character counting',
      'Reading time estimation',
      'Keyword density analysis',
      'Sentence and paragraph stats'
    ],
    longDescription: 'Get detailed insights into your text with comprehensive metrics.'
  },
  {
    id: 'plagiarism-checker',
    name: 'Plagiarism Checker',
    icon: '🔍',
    path: '/plagiarism-checker',
    category: ToolCategory.ANALYSIS_TOOLS,
    description: 'Scan for duplicate content across billions of web pages and academic databases.',
    features: [
      'Billions of sources checked',
      'Academic database integration',
      'Detailed similarity reports',
      'Source attribution'
    ],
    longDescription: 'Ensure content originality by scanning against billions of web pages.'
  },
  {
    id: 'readability-checker',
    name: 'Readability Checker',
    icon: '📖',
    path: '/readability-checker',
    category: ToolCategory.ANALYSIS_TOOLS,
    description: 'Analyze text readability with Flesch-Kincaid, Gunning Fog, and other standard metrics.',
    features: [
      'Multiple readability scores',
      'Grade level assessment',
      'Reading time calculation',
      'Improvement suggestions'
    ],
    longDescription: 'Optimize your content for your target audience with comprehensive readability analysis.'
  },
  {
    id: 'essay-checker',
    name: 'Essay Checker',
    icon: '🎓',
    path: '/essay-checker',
    category: ToolCategory.AI_DETECTION,
    description: 'Comprehensive essay analysis combining AI detection, grammar checking, and plagiarism scanning.',
    features: [
      'All-in-one essay analysis',
      'AI content detection',
      'Grammar and style review',
      'Plagiarism verification'
    ],
    longDescription: 'The ultimate essay review tool combining AI detection, grammar checking, and plagiarism scanning.'
  },
  {
    id: 'text-comparison',
    name: 'Text Comparison',
    icon: '🔄',
    path: '/text-comparison',
    category: ToolCategory.COMPARISON_TOOLS,
    description: 'Compare two texts side-by-side with highlighted differences and similarity scoring.',
    features: [
      'Visual diff highlighting',
      'Similarity percentage',
      'Word-by-word comparison',
      'Export comparison report'
    ],
    longDescription: 'Compare two pieces of text with precise, visual difference highlighting.'
  },
  {
    id: 'citation-generator',
    name: 'Citation Generator',
    icon: '📑',
    path: '/citation-generator',
    category: ToolCategory.WRITING_TOOLS,
    description: 'Generate accurate citations in APA, MLA, Chicago, and other academic styles instantly.',
    features: [
      'Multiple citation styles',
      'Auto-fill from URL',
      'Bibliography builder',
      'Export to Word/PDF'
    ],
    longDescription: 'Create perfectly formatted citations in seconds with support for major academic styles.'
  }
];

/**
 * Tools grouped by category
 */
export const TOOL_CATEGORIES: ToolCategoryGroup[] = [
  {
    category: ToolCategory.AI_DETECTION,
    label: 'AI Detection',
    description: 'Advanced tools for detecting and analyzing AI-generated content',
    tools: FOOTER_TOOLS.filter(tool => tool.category === ToolCategory.AI_DETECTION)
  },
  {
    category: ToolCategory.WRITING_TOOLS,
    label: 'Writing Tools',
    description: 'Essential tools for writing, editing, and improving content',
    tools: FOOTER_TOOLS.filter(tool => tool.category === ToolCategory.WRITING_TOOLS)
  },
  {
    category: ToolCategory.ANALYSIS_TOOLS,
    label: 'Analysis Tools',
    description: 'Comprehensive text analysis and quality assessment',
    tools: FOOTER_TOOLS.filter(tool => tool.category === ToolCategory.ANALYSIS_TOOLS)
  },
  {
    category: ToolCategory.COMPARISON_TOOLS,
    label: 'Comparison Tools',
    description: 'Tools for comparing and analyzing text differences',
    tools: FOOTER_TOOLS.filter(tool => tool.category === ToolCategory.COMPARISON_TOOLS)
  }
];

/**
 * Get popular tools
 */
export const getPopularTools = (): Tool[] => {
  return FOOTER_TOOLS.filter(tool => tool.isPopular);
};

/**
 * Get tool by ID
 */
export const getToolById = (id: string): Tool | undefined => {
  return FOOTER_TOOLS.find(tool => tool.id === id);
};

/**
 * Get tools by category
 */
export const getToolsByCategory = (category: ToolCategory): Tool[] => {
  return FOOTER_TOOLS.filter(tool => tool.category === category);
};
